<!DOCTYPE html>
<html>
<head>
<style>
table {
    text-align: center;
    border-collapse: collapse;
}
td, th {
    border: 1px solid #dddddd;
    padding: 8px;
}
.column_alignment
{
    word-break: break-all;
}

</style>
<h1>Device Offline Report</h1>
<h4>Generated By:{{$user_generated_by}} <br>{{$generated_by}}</h4><h4 style="position:absolute;left:520px;top:80px">Generated On: {{$generated_on}}</h4>
    <div style="position:absolute;left:520px;top:10px" class="cls_003">
        <img src="assets/images/smart_eclipse_logo.png" alt="Logo" height="30px" width="150px">
    </div>
</head>
<body>
@if(count($offline_devices) != 0)
<?php if($device_type == config("eclipse.DEVICE_STATUS.TAGGED")){$device_type = 'Tagged Devices';}elseif($device_type == config("eclipse.DEVICE_STATUS.UNTAGGED")){$device_type = 'Untagged Devices';}elseif($device_type == config("eclipse.DEVICE_STATUS.NOT_YET_ACTIVATED")){$device_type = 'Not Yet Activated';}else{$device_type = 'Tagged, Untagged, Not Yet Activated';}; ?>
    <h4 style="position:absolute;top:130px;bottom:30px;">Device Type:<br> {{$device_type}}</h4>
    <h4 style="position:absolute;top:130px;left:520px;bottom:30px;">Offline Duration:<br> <?php ( $offline_duration == null ) ? $offline_duration = '1 Hour' : $offline_duration = $offline_duration.' Hours'; ?>{{$offline_duration}}</h4>
    <br><br><br>
    <h2 style="margin-left:250px;">Device Details</h2>
    <?php $i = 1; ?>
    @foreach($offline_devices as $each_data)
    <h4 style="text-align: left;">#{{$i}}</h4>
    <table style="width:100%;text-align: left;">
        <tbody>
            <tr">
                <td><b>IMEI</b></td>
                <td><?php ( isset($each_data->imei) ) ? $imei = $each_data->imei : $imei='-NA-' ?>{{$imei}}</td>
            </tr>
            <tr">
                <td><b>Serial Number</b></td>
                <td><?php ( isset($each_data->serial_no) ) ? $serial_no = $each_data->serial_no : $serial_no='-NA-' ?>{{$serial_no}}</td>
            </tr>
            <tr>
                <td><b>Vehicle Name</b></td>
                <td class = 'column_alignment'><?php ( isset($each_data->vehicleGps->vehicle->name) ) ? $vehicle_name = $each_data->vehicleGps->vehicle->name : $vehicle_name='-NA-' ?>{{$vehicle_name}}</td>
            </tr>
            <tr>
                <td><b>Registration Number</b></td>
                <td class = 'column_alignment'><?php ( isset($each_data->vehicleGps->vehicle->register_number) ) ? $register_no = $each_data->vehicleGps->vehicle->register_number : $register_no='-NA-' ?>{{$register_no}}</td>
            </tr>
            <tr>
                <td><b>Last Packet Received On</b></td>
                <td><?php ( isset($each_data->device_time) ) ? $device_time = $each_data->device_time : $device_time='-Not Yet Activated-' ?>{{$device_time}}</td>
            </tr>
            <tr>
                <td><b>End User Name</b></td>
                <td class = 'column_alignment'><?php ( isset($each_data->gpsStock->client->name) ) ? $client = $each_data->gpsStock->client->name : $client='-NA-' ?>{{$client}}</td>
            </tr>
            <tr>
                <td><b>Distributor Name</b></td>
                <td class = 'column_alignment'><?php ( isset($each_data->gpsStock->dealer->name) ) ? $dealer = $each_data->gpsStock->dealer->name : $dealer='-NA-' ?>{{$dealer}}</td>
            </tr>
            <tr">
                <td><b>Dealer Name</b></td>
                <td class = 'column_alignment'><?php ( isset($each_data->gpsStock->subdealer->name) ) ? $subdealer = $each_data->gpsStock->subdealer->name : $subdealer='-NA-' ?>{{$subdealer}}</td>
            </tr>
            <tr>
                <td><b>Sub Dealer Name<b></td>
                <td class = 'column_alignment'><?php ( isset($each_data->gpsStock->trader->name) ) ? $trader = $each_data->gpsStock->trader->name : $trader='-NA-' ?>{{$trader}}</td>
            </tr>
            <tr>
                <td><b>Main Power Connected<b></td>
                <td class = 'column_alignment'>
                <?php 
                    if(isset($each_data->main_power_status))
                    {
                        ( $each_data->main_power_status == 1 ) ? $main_power_status = "YES" : $main_power_status = "NO";
                    }
                    else
                    {
                        $main_power_status = '-NA-';
                    }
                ?>{{$main_power_status}}</td>
            </tr>
        </tbody>
    </table>
    <?php $i++; ?>
    @endforeach
@endif

</body>
</html>
