<!DOCTYPE html>
<html>
<head>
<style>
table {
    text-align: center;
    border-collapse: collapse;
}
td, th {
    border: 1px solid #dddddd;
    padding: 8px;
}

</style>
<h1>Device Status Report (Online)</h1>
<h4>Generated By:<br> {{$generated_by}} <br>{{$manufactured_by}}</h4><h4 style="position:absolute;left:520px;top:80px">Generated On: {{$generated_on}}</h4>
    <div style="position:absolute;left:520px;top:10px" class="cls_003">
        <img src="assets/images/smart_eclipse_logo.png" alt="Logo" height="30px" width="150px">
    </div>
</head>
<body>
@if(count($device_online_report) != 0)
     <?php $i = 1; ?>   
     @foreach($device_online_report as $each_data)
    <h4 style="text-align: left;">#{{$i}}</h4>
    <table style="width:100%;text-align: left;">
        <tbody>
            <tr>
                <td><b>IMEI</b></td>
                <td><?php ( isset($each_data->imei) ) ? $imei = $each_data->imei : $imei='-NA-' ?>{{$imei}}</td>
            </tr>
            <tr>
                <td><b>Serial Number</b></td>
                <td><?php ( isset($each_data->serial_no) ) ? $serial_no = $each_data->serial_no : $serial_no='-NA-' ?>{{$serial_no}}</td>
            </tr>
            <tr>
                <td><b>Vehicle Name</b></td>
                <td><?php ( isset($each_data->vehicleGps->vehicle->name) ) ? $vehicle_name = $each_data->vehicleGps->vehicle->name : $vehicle_name='-NA-' ?>{{$vehicle_name}}</td>
            </tr>
            <tr>
                <td><b>Registration Number</b></td>
                <td><?php ( isset($each_data->vehicleGps->vehicle->register_number) ) ? $register_no = $each_data->vehicleGps->vehicle->register_number : $register_no='-NA-' ?>{{$register_no}}</td>
            </tr>
            <tr>
                <td><b>Last Packet Received On</b></td>
                <td><?php ( isset($each_data->device_time) ) ? $device_time = $each_data->device_time : $device_time='-Not Yet Activated-' ?>{{$device_time}}</td>
            </tr>
            <tr>
                <td><b>End User Name</b></td>
                <td><?php ( isset($each_data->vehicleGps->vehicle->client->name) ) ? $client_name = $each_data->vehicleGps->vehicle->client->name : $client_name='-NA-' ?>{{$client_name}}</td>
            </tr>
            <!-- {{$each_data->vehicleStock}} -->
            
            <tr>
                <td><b>End User Name</b></td>
                <td><?php ( isset($each_data->gpsStock->client->name) ) ? $client = $each_data->gpsStock->client->name : $client='-NA-' ?>{{$client}}</td>
            </tr>
            <tr>
                <td><b>Distributor Name</b></td>
                <td><?php ( isset($each_data->gpsStock->dealer->name) ) ? $dealer = $each_data->gpsStock->dealer->name : $dealer='-NA-' ?>{{$dealer}}</td>
            </tr>
            <tr>
                <td><b>Dealer Name</b></td>
                <td><?php ( isset($each_data->gpsStock->subdealer->name) ) ? $subdealer = $each_data->gpsStock->subdealer->name : $subdealer='-NA-' ?>{{$subdealer}}</td>
            </tr>
            <tr>
                <td><b>Sub Dealer Name/<b></td>
                <td><?php ( isset($each_data->gpsStock->trader->name) ) ? $trader = $each_data->gpsStock->trader->name : $trader='-NA-' ?>{{$trader}}</td>
            </tr>
            <tr>
                <td><b>Vehicle Status<b></td>
                <td><?php ( isset($each_data->mode) ) ? $mode = $each_data->mode : $mode='-NA-' ?>{{$mode}}</td>
            </tr>
        </tbody>
    </table>
    <?php $i++; ?>
    @endforeach
   
@endif

</body>
</html>

@section('script')
  
@endsection