<!DOCTYPE html>
<html>
<head>
<style>
table {
    text-align: center;
    border-collapse: collapse;
    width: 100%;
}
td, th {
    border: 1px solid #dddddd;
    padding: 8px;
}
.from_to
{
    text-align: left;
}

</style>
<h1>Device Stock Report</h1>
<h4>Generated By:<br> {{$generated_by}}</h4><h4 style="position:absolute;left:520px;top:80px">Generated On: {{$generated_on}}</h4>
  <div style="position:absolute;left:520px;top:10px" class="cls_003">
    <img src="assets/images/smart_eclipse_logo.png" alt="Logo" height="30px" width="150px">
  </div>
</head>
<body>
@if(count($stock_summary_details) != 0)
<br>
<h2 style="margin-left:250px;">Report Summary</h2>
<table>
  <thead>
    <tr>
      <th></th>
      <th>In Stock</th>
      <th>Stock To Accept</th>
    </tr>
  </thead>
  <tbody>
    <?php
        $total_instock          =   0;
        $total_stock_to_accept  =   0;
    ?>
    @foreach($stock_summary_details as $each_data)
        <tr>
            <td style="text-align:left;"><b>{{$each_data['user']}}</b></td>
            <td>{{$each_data['in_stock']}}</td>
            <td>{{$each_data['stock_to_accept']}}</td>
        </tr>
        <?php
            $total_instock          =   $total_instock+$each_data['in_stock'];
            if(is_int($each_data['stock_to_accept']))
            {
                $total_stock_to_accept  =   $total_stock_to_accept+$each_data['stock_to_accept'];
            }
        ?>
    @endforeach
    <tr style="background-color:#e4e4ea;">
        <td style="text-align:left;"><b>Total</b></td>
        <td><b>{{$total_instock}}</b></td>
        <td><b>{{$total_stock_to_accept}}</b></td>
    </tr>
  </tbody>
</table>
@endif
@if(count($stock_details_of_manufacturer) != 0 || count($stock_details_of_distributors) != 0 || count($stock_details_of_dealers) || count($stock_details_of_sub_dealers) != 0)
<br>
<h2 style="margin-left:250px;">Report Details</h2>
@endif
@if(count($stock_details_of_manufacturer) != 0)
<h3 style="text-align: center;"> Stock Details - Manufacturers</h3>
<table>
  <thead>
      <tr>
        <th>Manufacturer Name</th>
        <th>In Stock</th>
      </tr>
  </thead>
  <tbody>
    <?php
        $total_instock          =   0;
    ?>
    @foreach($stock_details_of_manufacturer as $each_data)
    <tr>
        <td><?php ( isset($each_data['user']) ) ? $manufacturer_name = $each_data['user'] : $manufacturer_name='-NA-' ?>{{$manufacturer_name}}</td>
        <td><?php ( isset($each_data['in_stock']) ) ? $in_stock = $each_data['in_stock'] : $in_stock='-NA-' ?>{{$in_stock}}</td>
    </tr>
    <?php
        $total_instock          =   $total_instock+$each_data['in_stock'];
    ?>
    @endforeach
    <tr style="background-color:#e4e4ea;">
        <td><b>Total</b></td>
        <td><b>{{$total_instock}}</b></td>
    </tr>
  </tbody>
</table>
@endif
@if(count($stock_details_of_distributors) != 0)
<h3 style="text-align: center;"> Stock Details - Distributors</h3>
<table>
  <thead>
      <tr>
        <th>Manufacturer Name</th>
        <th>Distributor Name</th>
        <th>In Stock</th>
        <th>Stock To Accept</th>
      </tr>
  </thead>
  <tbody>
    <?php
        $total_instock          =   0;
        $total_stock_to_accept  =   0;
    ?>
    @foreach($stock_details_of_distributors as $each_data)
    <tr>
        <td><?php ( isset($each_data['manufacturer_name']) ) ? $manufacturer_name = $each_data['manufacturer_name'] : $manufacturer_name='-NA-' ?>{{$manufacturer_name}}</td>
        <td><?php ( isset($each_data['distributor_name']) ) ? $distributor_name = $each_data['distributor_name'] : $distributor_name='-NA-' ?>{{$distributor_name}}</td>
        <td><?php ( isset($each_data['in_stock']) ) ? $in_stock = $each_data['in_stock'] : $in_stock='-NA-' ?>{{$in_stock}}</td>
        <td><?php ( isset($each_data['stock_to_accept']) ) ? $stock_to_accept = $each_data['stock_to_accept'] : $stock_to_accept='-NA-' ?>{{$stock_to_accept}}</td>
    </tr>
    <?php
        $total_instock          =   $total_instock+$each_data['in_stock'];
        if(is_int($each_data['stock_to_accept']))
        {
            $total_stock_to_accept  =   $total_stock_to_accept+$each_data['stock_to_accept'];
        }
    ?>
    @endforeach
    <tr style="background-color:#e4e4ea;">
        <td></td>
        <td><b>Total</b></td>
        <td><b>{{$total_instock}}</b></td>
        <td><b>{{$total_stock_to_accept}}</b></td>
    </tr>
  </tbody>
</table>
@endif
@if(count($stock_details_of_dealers) != 0)
<h3 style="text-align: center;"> Stock Details - Dealers</h3>
<table>
  <thead>
    <tr>
        <th>Distributor Name</th>
        <th>Dealer Name</th>
        <th>In Stock</th>
        <th>Stock To Accept</th>
    </tr>
  </thead>
  <tbody>
    <?php
        $total_instock          =   0;
        $total_stock_to_accept  =   0;
    ?>
    @foreach($stock_details_of_dealers as $each_data)
    <tr>
        <td><?php ( isset($each_data['distributor_name']) ) ? $distributor_name = $each_data['distributor_name'] : $distributor_name='-NA-' ?>{{$distributor_name}}</td>
        <td><?php ( isset($each_data['dealer_name']) ) ? $dealer_name = $each_data['dealer_name'] : $dealer_name='-NA-' ?>{{$dealer_name}}</td> 
        <td><?php ( isset($each_data['in_stock']) ) ? $in_stock = $each_data['in_stock'] : $in_stock='-NA-' ?>{{$in_stock}}</td>
        <td><?php ( isset($each_data['stock_to_accept']) ) ? $stock_to_accept = $each_data['stock_to_accept'] : $stock_to_accept='-NA-' ?>{{$stock_to_accept}}</td>
    </tr>
    <?php
        $total_instock          =   $total_instock+$each_data['in_stock'];
        if(is_int($each_data['stock_to_accept']))
        {
            $total_stock_to_accept  =   $total_stock_to_accept+$each_data['stock_to_accept'];
        }
    ?>
    @endforeach
    <tr style="background-color:#e4e4ea;">
        <td></td>
        <td><b>Total</b></td>
        <td><b>{{$total_instock}}</b></td>
        <td><b>{{$total_stock_to_accept}}</b></td>
    </tr>
  </tbody>
</table>
@endif
@if(count($stock_details_of_sub_dealers) != 0)
<h3 style="text-align: center;"> Stock Details - Sub Dealers</h3>
<table>
  <thead>
    <tr>
        <th>Dealer Name</th>
        <th>Sub Dealer Name</th>
        <th>In Stock</th>
        <th>Stock To Accept</th>
    </tr>
  </thead>
  <tbody>
    <?php
        $total_instock          =   0;
        $total_stock_to_accept  =   0;
    ?>
    @foreach($stock_details_of_sub_dealers as $each_data)
    <tr>
        <td><?php ( isset($each_data['dealer_name']) ) ? $dealer_name = $each_data['dealer_name'] : $dealer_name='-NA-' ?>{{$dealer_name}}</td> 
        <td><?php ( isset($each_data['sub_dealer_name']) ) ? $sub_dealer_name = $each_data['sub_dealer_name'] : $sub_dealer_name='-NA-' ?>{{$sub_dealer_name}}</td> 
        <td><?php ( isset($each_data['in_stock']) ) ? $in_stock = $each_data['in_stock'] : $in_stock='-NA-' ?>{{$in_stock}}</td>
        <td><?php ( isset($each_data['stock_to_accept']) ) ? $stock_to_accept = $each_data['stock_to_accept'] : $stock_to_accept='-NA-' ?>{{$stock_to_accept}}</td>
    </tr>
    <?php
        $total_instock          =   $total_instock+$each_data['in_stock'];
        if(is_int($each_data['stock_to_accept']))
        {
            $total_stock_to_accept  =   $total_stock_to_accept+$each_data['stock_to_accept'];
        }
    ?>
    @endforeach
    <tr style="background-color:#e4e4ea;">
        <td></td>
        <td><b>Total</b></td>
        <td><b>{{$total_instock}}</b></td>
        <td><b>{{$total_stock_to_accept}}</b></td>
    </tr>
  </tbody>
</table>
@endif


</body>
</html>