<!DOCTYPE html>
<html>
<head>
<style>
table {
  text-align: center;
  border-collapse: collapse;
}
td, th {
  border: 1px solid #dddddd;
  padding: 8px;
}

</style>
<h1>Device Return Report</h1>
<h4>Generated By:<br> {{$generated_by}}</h4><h4 style="position:absolute;left:520px;top:80px">Generated On: {{$generated_on}}</h4>
  <div style="position:absolute;left:520px;top:10px" class="cls_003">
    <img src="assets/images/smart_eclipse_logo.png" alt="Logo" height="30px" width="150px">
  </div>
</head>
<body>
@if(count($return_details) != 0)
<h4 style="position:absolute;top:130px;bottom:30px;">Date Range:<br> {{$from_date}} to {{$to_date}}</h4>
<br><br><br>
<h2 style="margin-left:250px;">Report Summary</h2>
<table style="width: 100%;text-align: left;">
  <thead>
    <tr>
      <td><b>End User Name</b></td>
      <td><b>Count</b></td>
    </tr>
  </thead>
  <tbody>
    @foreach($return_details as $each_data)
      <tr style = "word-wrap: break-word;">
        <td><?php ( isset($each_data->client_name) ) ? $client_name = $each_data->client_name : $client_name='-NA-' ?>{{$client_name}}</td>
        <td><b>{{$each_data->count}}</b></td>
      </tr>
      @endforeach
  </tbody>
</table>
@endif
@if(count($return_details) != 0)
<br>
<h2 style="margin-left:250px;">Report Details</h2>
@endif
@if(count($return_device_manufactured) != 0)
<h3 style="text-align: center;">Device List - Manufactured On</h3>
<table style="width: 100%;">
    <thead>
        <tr>
            <th>Manufactured On</th>
            <th>Count</th>
        </tr>
    </thead>
  <tbody>
    @foreach($return_device_manufactured as $each_data)
    <tr style = "word-wrap: break-word;">
        <td>{{date('d-m-Y',strtotime($each_data->manufacturing_date))}}</td>
        <td>{{$each_data->count}}</td>
    </tr>
    @endforeach
  </tbody>
</table>
@endif
@if(count($return_details) != 0)
<h3 style="text-align: center;">Device List - Transferred Details</h3>
<table style="width: 100%;">
    <thead>
        <tr>
            <th>Manufacturer Name</th>
            <th>Distributor Name</th>
            <th>Dealer Name</th>
            <th>Sub Dealer Name</th>
            <th>End User Name</th>
            <th>Count</th>
        </tr>
    </thead>
  <tbody>
    @foreach($return_details as $each_data)
    <tr style = "word-wrap: break-word;">
        <td><?php ( isset($each_data->manufacturer_name) ) ? $manufacturer_name = $each_data->manufacturer_name : $manufacturer_name='-NA-' ?>{{$manufacturer_name}}</td>
        <td><?php ( isset($each_data->distributor_name) ) ? $distributor_name = $each_data->distributor_name : $distributor_name='-NA-' ?>{{$distributor_name}}</td>
        <td><?php ( isset($each_data->dealer_name) ) ? $dealer_name = $each_data->dealer_name : $dealer_name='-NA-' ?>{{$dealer_name}}</td>
        <td><?php ( isset($each_data->sub_dealer_name) ) ? $sub_dealer_name = $each_data->sub_dealer_name : $sub_dealer_name='-NA-' ?>{{$sub_dealer_name}}</td>
        <td><?php ( isset($each_data->client_name) ) ? $client_name = $each_data->client_name : $client_name='-NA-' ?>{{$client_name}}</td>
        <td>{{$each_data->count}}</td>
    </tr>
    @endforeach
  </tbody>
</table>
@endif
@if(count($return_details) != 0)
<h3 style="text-align: center;">Device List - Transferred Details</h3>
<?php $i = 1; ?>
@foreach($return_device_details as $each_data)
<h4 style="text-align: left;">#{{$i}}</h4>
<table style="width:100%;text-align: left;">
    <tbody>
      <tr>
          <td><b>Returned On</b></td>
          <td style = "word-wrap: break-word;">{{date('d/m/Y',strtotime($each_data->returned_on))}}</td>
      </tr>
      <tr>
          <td><b>IMEI</b></td>
          <td style = "word-wrap: break-word;">{{$each_data->imei}}</td>
      </tr>
      <tr>
          <td><b>Serial Number</b></td>
          <td style = "word-wrap: break-word;">{{$each_data->serial_number}}</td>
      </tr>
      <tr>
          <td><b>Manufacturer Name</b></td>
          <td style = "word-wrap: break-word;"><?php ( isset($each_data->manufacturer_name) ) ? $manufacturer_name = $each_data->manufacturer_name : $manufacturer_name='-NA-' ?>{{$manufacturer_name}}</td>
      </tr>
      <tr>
          <td><b>Distributor Name<b></td>
          <td style = "word-wrap: break-word;"><?php ( isset($each_data->distributor_name) ) ? $distributor_name = $each_data->distributor_name : $distributor_name='-NA-' ?>{{$distributor_name}}</td>
      </tr>
      <tr>
          <td><b>Dealer Name</b></td>
          <td style = "word-wrap: break-word;"><?php ( isset($each_data->dealer_name) ) ? $dealer_name = $each_data->dealer_name : $dealer_name='-NA-' ?>{{$dealer_name}}</td>
      </tr>
      <tr>
          <td><b>Sub Dealer Name</b></td>
          <td style = "word-wrap: break-word;"><?php ( isset($each_data->sub_dealer_name) ) ? $sub_dealer_name = $each_data->sub_dealer_name : $sub_dealer_name='-NA-' ?>{{$sub_dealer_name}}</td>
      </tr>
      <tr>
          <td><b>End User Name</b></td>
          <td style = "word-wrap: break-word;"><?php ( isset($each_data->client_name) ) ? $client_name = $each_data->client_name : $client_name='-NA-' ?>{{$client_name}}</td>
      </tr>
      <tr>
          <td><b>Service Engineer Name</b></td>
          <td style = "word-wrap: break-word;">{{$each_data->servicer_name}}</td>
      </tr>
    </tbody>
</table>
<?php $i++; ?>
@endforeach
@endif

</body>
</html>
