<!DOCTYPE html>
<html>
<head>
<style>
table {
  text-align: center;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  padding: 8px;
}
.from_to
{
  text-align: left;
}

</style>
<h1>Transferred Device Report</h1>
<h4>Generated By:<br> {{$generated_by}}</h4><h4 style="position:absolute;left:520px;top:80px">Generated On: {{$generated_on}}</h4>
  <div style="position:absolute;left:520px;top:10px" class="cls_003">
    <img src="assets/images/smart_eclipse_logo.png" alt="Logo" height="30px" width="150px">
  </div>
</head>
<body>
@if(count($transaction_details) != 0)
<h4 style="position:absolute;top:130px;bottom:30px;">Date Range:<br> {{$from_date}} to {{$to_date}}</h4>
<h4 style="position:absolute;top:180px;bottom:100px;">From User: {{$transfer_from}} &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; To User: {{$transfer_to}}</h4>
<br><br><br><br>


<?php $i = 1; ?>
@foreach($transaction_details as $each_data)
<h4 style="text-align: left;">#{{$i}}</h4>
<table style="width:100%;text-align: left;">
    <tbody>
      <tr>
          <td><b>Transferred On</b></td>
          <td style = "word-wrap: break-word;"><?php ( isset($each_data->dispatched_on) ) ? $dispatched_on = date('d-m-Y',strtotime($each_data->dispatched_on)) : $dispatched_on='-NA-' ?>{{$dispatched_on}}</td>
      </tr>
      <tr>
          <td><b>IMEI</b></td>
          <td style = "word-wrap: break-word;"><?php ( isset($each_data->imei) ) ? $imei = $each_data->imei : $imei='-NA-' ?>{{$imei}}</td>
      </tr>
      <tr>
          <td><b>Serial Number</b></td>
          <td style = "word-wrap: break-word;"><?php ( isset($each_data->serial_no) ) ? $serial_no = $each_data->serial_no : $serial_no='-NA-' ?>{{$serial_no}}</td>
      </tr>
      <tr>
          <td><b>Order Number</b></td>
          <td style = "word-wrap: break-word;"><?php ( isset($each_data->order_number) ) ? $order_number = $each_data->order_number : $order_number='-NA-' ?>{{$order_number}}</td>
      </tr>
      <tr>
          <td><b>Invoice Number<b></td>
          <td style = "word-wrap: break-word;"><?php ( isset($each_data->invoice_number) ) ? $invoice_number = $each_data->invoice_number : $invoice_number='-NA-' ?>{{$invoice_number}}</td>
      </tr>
      <tr>
          <td><b>Scanned Employee Code</b></td>
          <td style = "word-wrap: break-word;"><?php ( isset($each_data->scanned_employee_code) ) ? $scanned_employee_code = $each_data->scanned_employee_code : $scanned_employee_code='-NA-' ?>{{$scanned_employee_code}}</td>
      </tr>
      <tr>
          <td><b>Transaction Accepted On</b></td>
          <td style = "word-wrap: break-word;"><?php ( isset($each_data->accepted_on) ) ? $accepted_on = date('d-m-Y',strtotime($each_data->accepted_on)) : $accepted_on='Awaiting Transfer Confirmation' ?>{{$accepted_on}}</td>
      </tr>
    </tbody>
</table>
<?php $i++; ?>
@endforeach
@endif

</body>
</html>