<!DOCTYPE html>
<html>
<head>
<style>
table {
  text-align: center;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  padding: 8px;
}
.from_to
{
  text-align: left;
}

</style>
<h2>Device Plan Expiry Report </h2>
<h4>Generated By:<br> {{$generated_by}}</h4>
<h4 style="position:absolute;left:520px;top:80px">Generated On: {{$generated_on}}</h4>
  <div style="position:absolute;left:520px;top:10px" class="cls_003">
    <img src="assets/images/smart_eclipse_logo.png" alt="Logo" height="30px" width="150px">
  </div>
</head>
<body>

<h4 style="position:absolute;top:130px;bottom:30px;">Date Range:<br> {{$from_date}} To {{$to_date}}</h4>
<br><br><br>
<h3 style="margin-left:250px;">Report Summary</h3>
<table>
<tbody style="text-align:left;">
    <tr>
        <td>Plan name </td> 
        <td style="text-align:center;">Number of devices</td>
    </tr>
    @foreach(config('eclipse.PLANS') as $each_plan)
    <tr>
        <td>{{ucfirst(strtolower($each_plan['NAME']))}} </td>
        <td style="text-align:center;"> <?php (isset($role_count[$each_plan['ID']])) ? $plan = $role_count[$each_plan['ID']]['count']: $plan = 0;?>{{ $plan}}</td>
    </tr>   
    @endforeach
    <tr>
        <td>Total</td>
        <td style="text-align:center;"><?php ($role_count_total)? $total=$role_count_total:$total=0?>{{$total}}</td>
    </tr>
  </tbody>
</table>

<h3 style="margin-left:250px;">Report Details</h3>
<p style="margin-top:30px;margin-bottom:30px;"><b>Device Details -</b> Plan expiring between {{$from_date}} to {{$to_date}}</p>

<?php $i = 1; ?> 

  
<!-- <h4 style="text-align: left;">#{{$i}}</h4> -->
<table style="width:100%;text-align: left;">
  <tbody>
    <tr>
        <th>Client name</th>
        <th>IMEI </td> 
        <th>Plan Name</th>
        <th>Expire On</th>
    </tr>
    @foreach($esim_lists as $item)
    <?php
  
    if($item->vehicles)
    {
        if($item->vehicles->client)
        {
            $plan_names     = array_column(config('eclipse.PLANS'), 'NAME', 'ID');
            $plan_name      = $plan_names[$item->vehicles->client->user->role ? $item->vehicles->client->user->role : 0];                          
            $result = $item->vehicles->client->name ;
        }
        else{
            $result = "NA"; 
            $plan_name="NA";
        }
    }
    else{
        $result = "NA";
        $plan_name="NA";
    }
    ?>  
    <tr>
        <td>{{$result}}</td>
        <td>{{$item->imei}}</td> 
        <td>{{$plan_name}}</td>
        <td>{{$item->expire_on}}</td>
    </tr>
    @endforeach
    @if(count($esim_lists) == 0)
      <tr>
        <td colspan="4" style="text-align: center;"><b>No Data Available</b></td>
      </tr>
      @endif
  </tbody>
  
</table>


</body>
</html>