<!DOCTYPE html>
<html>
<head>
<style>
table {
  text-align: center;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  padding: 8px;
}
.from_to
{
  text-align: left;
}

</style>
<h1>Device Plan Expiry Report </h1>
<h4>Generated By:<br> VST Mobility Solutions (Manufacturer)</h4>
<h4 style="position:absolute;left:520px;top:80px">Generated On: {{$generated_on}}</h4>
  <div style="position:absolute;left:520px;top:10px" class="cls_003">
    <img src="assets/images/smart_eclipse_logo.png" alt="Logo" height="30px" width="150px">
  </div>
</head>
<body>

<h4 style="position:absolute;top:130px;bottom:30px;">Date Range:<br> {{$from_date}} to {{$to_date}}</h4>

<br><br><br>
<h2 style="margin-left:250px;">Report Summary</h2>

<table>
<tbody style="text-align:left;">
    <tr>
        <td>Plan name </td> 
        <td style="text-align:center;">Number of devices</td>
    </tr>
    
    <tr>
        <td>Freebies</td>
        <td style="text-align:center;">{{$role_count[0]['count']}}</td>
    </tr>
    <tr>
        <td>Fundamental</td>
        <td style="text-align:center;">{{$role_count[1]['count']}}</td>
    </tr>
    <tr>
        <td>Superior</td>
        <td style="text-align:center;">{{$role_count[2]['count']}}</td>
    </tr>
    <tr>
        <td>Pro</td>
        <td style="text-align:center;">{{$role_count[3]['count']}}</td>
    </tr>
    <tr>
        <td>Total</td>
        <td style="text-align:center;">{{$role_count_total}}</td>
    </tr>
  </tbody>
</table>

<h2 style="margin-left:250px;">Report Details</h2>
<p style="margin-top:30px;margin-bottom:30px;"><b>Device Details -</b> Plan expiring between {{$from_date}} to {{$to_date}}</p>

<?php $i = 1; ?> 

  
<!-- <h4 style="text-align: left;">#{{$i}}</h4> -->
<table style="width:100%;text-align: left;">
  <tbody>
    <tr>
        <th>Client name</th>
        <th>IMEI </td> 
        <th>Plan Name</th>
        <th>Expire On</th>
    </tr>
    @foreach($esim_lists as $item)
    <?php
  
    if($item->gps->gpsStock)
    {
        if($item->gps->gpsStock->client)
        {
            $plan_names     = array_column(config('eclipse.PLANS'), 'NAME', 'ID');
            $plan_name      = $plan_names[$item->gps->gpsStock->client->user->role ? $item->gps->gpsStock->client->user->role : 0];                          
            $result = $item->gps->gpsStock->client->name ;
        }
        else{
            $result = "NA"; 
            $plan_name="NA";
        }
    }
    else{
        $result = "NA";
        $plan_name="NA";
    }
    ?>  
    <tr>
        <td>{{$result}}</td>
        <td>{{$item->imei}}</td> 
        <td>{{$plan_name}}</td>
        <td>{{$item->expire_on}}</td>
    </tr>
    <?php //$i++; ?>
@endforeach
  </tbody>
  
</table>


</body>
</html>